baseurl                  = "https://example.com"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Lion's Portfolio"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "Call me Sam, a theme for Hugo."

# Metadata for Open Graph and Twitter
    description          = "Lion's Portfolio"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Lion's Portfolio"
    # rss                = ""

[[params.mainMenu]]
    link = "about"
    text = "about me"

[[params.mainMenu]]
    link = "posts"
    text = "portfolio"

[imaging]
    quality = 75
